---
- name: Deploy Semaphore using Docker
  hosts: all
  become: true
  tasks:
    - name: Installation de Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Installation de Docker Compose
      apt:
        name: docker-compose
        state: present
        update_cache: yes

    - name: Verification que docker est actif
      service:
        name: docker
        state: started
        enabled: yes

    - name: Creation du repertoire pour dockercompose
      file:
        path: /opt/semaphore
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Creation du fichier dockercompose
      copy:
        dest: /opt/semaphore/docker-compose.yml
        content: |
          version: '3'
          services:
            semaphore:
              ports:
                - "3000:3000"
              image: semaphoreui/semaphore:latest
              environment:
                SEMAPHORE_DB_DIALECT: bolt
                SEMAPHORE_ADMIN: admin
                SEMAPHORE_ADMIN_PASSWORD: admin
                SEMAPHORE_ADMIN_NAME: Admin
                SEMAPHORE_ADMIN_EMAIL: admin@localhost

    - name: Demarrage de semaphore via dockercompose
      command: docker-compose up -d
      args:
        chdir: /opt/semaphore

    - name: Verification du contenair docker
      docker_container:
        name: semaphore
        image: semaphoreui/semaphore:latest
        state: started
        ports:
          - "3000:3000"
        env:
          SEMAPHORE_DB_DIALECT: bolt
          SEMAPHORE_ADMIN: admin
          SEMAPHORE_ADMIN_PASSWORD: admin
          SEMAPHORE_ADMIN_NAME: Admin
          SEMAPHORE_ADMIN_EMAIL: admin@localhost
